# Generated by Django 4.2.7 on 2023-11-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hotel_hotelimages_hotelbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotelimages',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='HotelBooking',
        ),
        migrations.DeleteModel(
            name='HotelImages',
        ),
    ]
